### ISSUE TITLE
Linked Demo Not Working

### ISSUE THREAD

**Issue by pragmat1c** [MathiasWP/svelte-idle#2]
Hi, 
Just thought you'd like to know the demo you have linked from the project doesn't seem to work.

https://svelte.dev/repl/005264a7de2446728aee059bb6fcbc46?version=3.46.4

Using chrome  104.0.5112.102

$idle is never true.

![image](https://user-images.githubusercontent.com/1749623/186255460-39f1c328-039a-4cd9-8d4f-bccfb927e887.png)

**Comment by pragmat1c** [comment]
https://svelte.dev/repl/2556416ff1ef4788a6591823f953b276?version=3.46.4

It was just an issue with the config. See updated demo in link.

**Comment by MathiasWP** [comment]
Thank you!
