### ISSUE TITLE
What if i want to start/stop idleness tracking based on an event ?

### ISSUE THREAD

**Issue by omeryousaf** [MathiasWP/svelte-idle#3]
I want to update timer value based on the data i receive from an network call, and the new value might be 0 meaning i need to stop tracking idleness, and then again after a while there could be another value coming in from the server requiring me to start tracking again. How do i do it ? If i call listen() multiple times but onIdle() only once, is that ok or do i need to unsubscribe previous subscription and resubscribe every time i issue a new call to listen() ?

**Comment by MathiasWP** [comment]
> I want to update timer value based on the data i receive from an network call, and the new value might be 0 meaning i need to stop tracking idleness, and then again after a while there could be another value coming in from the server requiring me to start tracking again. How do i do it ? If i call listen() multiple times but onIdle() only once, is that ok or do i need to unsubscribe previous subscription and resubscribe every time i issue a new call to listen() ?

You could call `listen()` to update the timeout duration with the current implementation, but it would not reset the the timers. 

I can expose the methods for clearing and starting the countdown, so that you can have more control over this functionality. I could also expose an "update config" method, so that you can set new values for the countdown.

**Comment by MathiasWP** [comment]
This has now been added in version 3, alongside with Svelte 4 support: https://github.com/MathiasWP/svelte-idle/commit/4d72cbdf039e399d2e79b4e02380788cdb1ed800

**Comment by omeryousaf** [comment]
Wow, thanks for the quick turnaround. Let me try those APIs.

**Comment by omeryousaf** [comment]
@MathiasWP isn't the `restartCountdown()` redundant ? Isn't calling `listen()` again going to restart a stopped countdown, too ?
