### ISSUE TITLE
stopCountdown is not stopping idle detection service

### ISSUE THREAD

**Issue by omeryousaf** [MathiasWP/svelte-idle#4]
## Expected
Running `stopCountdown()` should stop the idle detection service until another listen() or updateOptions() or restartCountdown() cmd is run.

## Actual
Running `stopCountdown()` keeps the idle detection on.

**Comment by omeryousaf** [comment]
@MathiasWP plz correct me if my understanding of `stopCountdown()` is incorrect. I assume it is supposed to stop the idle tracking until it is restarted as mentioned in the `Expected` section of the issue description.

**Comment by MathiasWP** [comment]
Should be fixed in v3.0.1

**Comment by omeryousaf** [comment]
@MathiasWP shouldn't the issue be closed after the fix is released ? Looking forward to v3.0.1 btw. Do we have an eta for it ?
UPDATE: plz ignore this message, i think i did not notice a new commit but i see it now. v3.0.1 is already out. Going to test it now.

**Comment by omeryousaf** [comment]
@MathiasWP which version of svelte-idle is being used by https://svelte.dev/repl/ed42876b89f9426a9795d94b374d37e1?version=4.2.19 ? The `stopCountdown()` doesn't seem to be working.
UPDATE: i had used it outside onMount right after calling initial listen() call, that's probably y it wasn't taking effect
```
listen({
	timer: idleTimeout
})
stopCountdown();
```
When i moved `stopCountdown()` into onMount, it worked
```
listen({
	timer: idleTimeout
})


onMount(() => {
	stopCountdown();
	const unsubscribe = onIdle(() => {
		onIdle(() => alert('USER IS IDLE'))
	});
	return unsubscribe;
})
```

UPDATE2: Well, just tested again and yes it seems `stopCountdown()` is not stopping the idle tracking. @MathiasWP i have reproduced it in https://svelte.dev/repl/ed42876b89f9426a9795d94b374d37e1?version=4.2.19. Plz check. It also seems `onIdle` is being called more than once now after every new idle timeout, feels like a memory leak in ur fix.

**Comment by omeryousaf** [comment]
@MathiasWP were u able to look into update2 in my prev comment ?

> i have reproduced it in https://svelte.dev/repl/ed42876b89f9426a9795d94b374d37e1?version=4.2.19. Plz check. It also seems onIdle is being called more than once now after every new idle timeout, feels like a memory leak in ur fix.
